"""Full hostel-mess item master: (name, default_unit, category)."""
CATEGORIES = [
    "Grains & Flour",
    "Dal & Pulses",
    "Vegetables",
    "Oil & Ghee",
    "Spices & Masala",
    "Dairy & Eggs",
    "Bakery",
    "Fuel",
    "Beverages",
    "Fruits",
    "Cleaning",
    "Disposables",
    "Pickles & Sauces",
    "Other",
]

DEFAULT_ITEMS = [
    # Grains & Flour
    ("Rice", "KG", "Grains & Flour"),
    ("Wheat Flour", "KG", "Grains & Flour"),
    ("Maida", "KG", "Grains & Flour"),
    ("Suji", "KG", "Grains & Flour"),
    ("Poha", "KG", "Grains & Flour"),
    ("Besan", "KG", "Grains & Flour"),
    ("Daliya", "KG", "Grains & Flour"),
    ("Bajra Flour", "KG", "Grains & Flour"),
    ("Jowar Flour", "KG", "Grains & Flour"),
    ("Ragi Flour", "KG", "Grains & Flour"),
    ("Murmura", "KG", "Grains & Flour"),
    ("Sabudana", "KG", "Grains & Flour"),
    ("Macaroni", "PACKET", "Grains & Flour"),
    ("Pasta", "PACKET", "Grains & Flour"),
    # Dal & Pulses
    ("Toor Dal", "KG", "Dal & Pulses"),
    ("Moong Dal", "KG", "Dal & Pulses"),
    ("Chana Dal", "KG", "Dal & Pulses"),
    ("Urad Dal", "KG", "Dal & Pulses"),
    ("Masoor Dal", "KG", "Dal & Pulses"),
    ("Rajma", "KG", "Dal & Pulses"),
    ("Kabuli Chana", "KG", "Dal & Pulses"),
    ("Soyabean", "KG", "Dal & Pulses"),
    ("Lobiya", "KG", "Dal & Pulses"),
    ("White Peas", "KG", "Dal & Pulses"),
    ("Moong Sabut", "KG", "Dal & Pulses"),
    ("Urad Sabut", "KG", "Dal & Pulses"),
    ("Kala Chana", "KG", "Dal & Pulses"),
    ("Masoor Sabut", "KG", "Dal & Pulses"),
    ("Split Peas", "KG", "Dal & Pulses"),
    # Vegetables
    ("Potato", "KG", "Vegetables"),
    ("Onion", "KG", "Vegetables"),
    ("Tomato", "KG", "Vegetables"),
    ("Mixed Vegetables", "KG", "Vegetables"),
    ("Cauliflower", "KG", "Vegetables"),
    ("Cabbage", "KG", "Vegetables"),
    ("Carrot", "KG", "Vegetables"),
    ("Green Peas", "KG", "Vegetables"),
    ("Brinjal", "KG", "Vegetables"),
    ("Ladyfinger", "KG", "Vegetables"),
    ("Pumpkin", "KG", "Vegetables"),
    ("Spinach", "KG", "Vegetables"),
    ("Green Chilli", "KG", "Vegetables"),
    ("Ginger", "KG", "Vegetables"),
    ("Garlic", "KG", "Vegetables"),
    ("Coriander Leaves", "GRAM", "Vegetables"),
    ("Mint Leaves", "GRAM", "Vegetables"),
    ("Curry Leaves", "GRAM", "Vegetables"),
    ("Lemon", "PIECE", "Vegetables"),
    ("Cucumber", "KG", "Vegetables"),
    ("Capsicum", "KG", "Vegetables"),
    ("French Beans", "KG", "Vegetables"),
    ("Bitter Gourd", "KG", "Vegetables"),
    ("Bottle Gourd", "KG", "Vegetables"),
    ("Ridge Gourd", "KG", "Vegetables"),
    ("Drumstick", "KG", "Vegetables"),
    ("Raw Banana", "KG", "Vegetables"),
    ("Sweet Potato", "KG", "Vegetables"),
    ("Radish", "KG", "Vegetables"),
    ("Beetroot", "KG", "Vegetables"),
    ("Mushroom", "PACKET", "Vegetables"),
    ("Coconut", "PIECE", "Vegetables"),
    ("Kathal", "KG", "Vegetables"),
    ("Tinda", "KG", "Vegetables"),
    ("Parwal", "KG", "Vegetables"),
    ("Suran", "KG", "Vegetables"),
    ("Kundru", "KG", "Vegetables"),
    ("Sem Beans", "KG", "Vegetables"),
    ("Methi Saag", "KG", "Vegetables"),
    ("Bathua Saag", "KG", "Vegetables"),
    ("Arbi", "KG", "Vegetables"),
    ("Kairi", "KG", "Vegetables"),
    ("Green Mango Powder", "GRAM", "Vegetables"),
    ("Turnip", "KG", "Vegetables"),
    ("Green Chickpeas", "KG", "Vegetables"),
    ("Mustard Greens", "KG", "Vegetables"),
    ("Amaranth Greens", "KG", "Vegetables"),
    ("Arhar Pods", "KG", "Vegetables"),
    ("Cluster Beans", "KG", "Vegetables"),
    ("Raw Papaya", "KG", "Vegetables"),
    ("Zucchini", "KG", "Vegetables"),
    ("Broccoli", "KG", "Vegetables"),
    ("Celery", "KG", "Vegetables"),
    ("Lettuce", "KG", "Vegetables"),
    ("Spring Onion", "KG", "Vegetables"),
    ("Leek", "KG", "Vegetables"),
    ("Turnip Greens", "KG", "Vegetables"),
    ("Radish Greens", "KG", "Vegetables"),
    # Oil & Ghee
    ("Cooking Oil", "LITRE", "Oil & Ghee"),
    ("Mustard Oil", "LITRE", "Oil & Ghee"),
    ("Soybean Oil", "LITRE", "Oil & Ghee"),
    ("Refined Oil", "LITRE", "Oil & Ghee"),
    ("Sunflower Oil", "LITRE", "Oil & Ghee"),
    ("Groundnut Oil", "LITRE", "Oil & Ghee"),
    ("Sesame Oil", "LITRE", "Oil & Ghee"),
    ("Coconut Oil", "LITRE", "Oil & Ghee"),
    ("Vanaspati", "PACKET", "Oil & Ghee"),
    ("Ghee", "KG", "Oil & Ghee"),
    # Spices & Masala
    ("Salt", "KG", "Spices & Masala"),
    ("Turmeric", "GRAM", "Spices & Masala"),
    ("Red Chilli", "GRAM", "Spices & Masala"),
    ("Coriander Powder", "GRAM", "Spices & Masala"),
    ("Cumin", "GRAM", "Spices & Masala"),
    ("Garam Masala", "GRAM", "Spices & Masala"),
    ("Mixed Spices", "GRAM", "Spices & Masala"),
    ("Mustard Seeds", "GRAM", "Spices & Masala"),
    ("Fenugreek Seeds", "GRAM", "Spices & Masala"),
    ("Fennel Seeds", "GRAM", "Spices & Masala"),
    ("Hing", "GRAM", "Spices & Masala"),
    ("Black Pepper", "GRAM", "Spices & Masala"),
    ("Amchur", "GRAM", "Spices & Masala"),
    ("Black Salt", "GRAM", "Spices & Masala"),
    ("Chaat Masala", "GRAM", "Spices & Masala"),
    ("Sambar Masala", "GRAM", "Spices & Masala"),
    ("Elaichi", "GRAM", "Spices & Masala"),
    ("Laung", "GRAM", "Spices & Masala"),
    ("Dalchini", "GRAM", "Spices & Masala"),
    ("Tej Patta", "GRAM", "Spices & Masala"),
    ("Ajwain", "GRAM", "Spices & Masala"),
    ("Kasuri Methi", "GRAM", "Spices & Masala"),
    ("Til", "GRAM", "Spices & Masala"),
    ("Imli", "KG", "Spices & Masala"),
    ("Sendha Namak", "KG", "Spices & Masala"),
    ("Jeera Powder", "GRAM", "Spices & Masala"),
    ("Dhaniya Powder", "GRAM", "Spices & Masala"),
    ("Red Chilli Powder", "GRAM", "Spices & Masala"),
    ("Chhole Masala", "GRAM", "Spices & Masala"),
    ("Kitchen King", "GRAM", "Spices & Masala"),
    ("Biryani Masala", "GRAM", "Spices & Masala"),
    ("Ketchup", "BOTTLE", "Spices & Masala"),
    ("Soy Sauce", "BOTTLE", "Spices & Masala"),
    ("Vinegar", "BOTTLE", "Spices & Masala"),
    ("Coconut Powder", "GRAM", "Spices & Masala"),
    ("Custard Powder", "GRAM", "Spices & Masala"),
    ("Coriander Seeds", "GRAM", "Spices & Masala"),
    ("White Pepper", "GRAM", "Spices & Masala"),
    ("Black Cardamom", "GRAM", "Spices & Masala"),
    ("Nigella Seeds", "GRAM", "Spices & Masala"),
    ("Sabzi Masala", "GRAM", "Spices & Masala"),
    ("Ginger Powder", "GRAM", "Spices & Masala"),
    ("Onion Powder", "GRAM", "Spices & Masala"),
    ("Garlic Powder", "GRAM", "Spices & Masala"),
    # Dairy & Eggs
    ("Milk", "LITRE", "Dairy & Eggs"),
    ("Paneer", "KG", "Dairy & Eggs"),
    ("Curd", "KG", "Dairy & Eggs"),
    ("Butter", "GRAM", "Dairy & Eggs"),
    ("Milk Powder", "PACKET", "Dairy & Eggs"),
    ("Egg", "DOZEN", "Dairy & Eggs"),
    ("Khoya", "KG", "Dairy & Eggs"),
    ("Chaas", "LITRE", "Dairy & Eggs"),
    # Bakery
    ("Bread", "PACKET", "Bakery"),
    ("Biscuits", "PACKET", "Bakery"),
    ("Buns", "PACKET", "Bakery"),
    ("Rusk", "PACKET", "Bakery"),
    ("Namkeen", "PACKET", "Bakery"),
    ("Noodles", "PACKET", "Bakery"),
    ("Sev", "PACKET", "Bakery"),
    ("Bhujia", "PACKET", "Bakery"),
    ("Chips", "PACKET", "Bakery"),
    ("Cornflakes", "PACKET", "Bakery"),
    ("Baking Soda", "GRAM", "Bakery"),
    ("Baking Powder", "GRAM", "Bakery"),
    ("Yeast", "GRAM", "Bakery"),
    ("Vermicelli", "PACKET", "Grains & Flour"),
    ("Oats", "PACKET", "Grains & Flour"),
    ("Cornflour", "PACKET", "Grains & Flour"),
    ("Rice Flour", "KG", "Grains & Flour"),
    ("Basmati Rice", "KG", "Grains & Flour"),
    ("Maize", "KG", "Grains & Flour"),
    ("Sattu", "KG", "Grains & Flour"),
    # Fuel
    ("Gas Cylinder", "PIECE", "Fuel"),
    # Beverages
    ("Tea", "GRAM", "Beverages"),
    ("Coffee", "GRAM", "Beverages"),
    ("Sugar", "KG", "Beverages"),
    ("Mishri", "KG", "Beverages"),
    ("Chocolate Powder", "PACKET", "Beverages"),
    ("Jaggery", "KG", "Beverages"),
    ("Honey", "BOTTLE", "Beverages"),
    ("Sharbat", "BOTTLE", "Beverages"),
    # Fruits (mess me kabhi-kabhi phal bhi banta hai)
    ("Banana", "DOZEN", "Fruits"),
    ("Apple", "KG", "Fruits"),
    ("Orange", "KG", "Fruits"),
    ("Guava", "KG", "Fruits"),
    ("Papaya", "KG", "Fruits"),
    ("Mango", "KG", "Fruits"),
    ("Grapes", "KG", "Fruits"),
    ("Pomegranate", "KG", "Fruits"),
    ("Watermelon", "KG", "Fruits"),
    ("Pineapple", "PIECE", "Fruits"),
    # Cleaning (mess safai ka samaan bhi bazaar se aata hai)
    ("Detergent Powder", "PACKET", "Cleaning"),
    ("Dish Soap", "PIECE", "Cleaning"),
    ("Floor Cleaner", "BOTTLE", "Cleaning"),
    ("Garbage Bags", "PACKET", "Cleaning"),
    ("Broom", "PIECE", "Cleaning"),
    ("Mop", "PIECE", "Cleaning"),
    ("Toilet Cleaner", "BOTTLE", "Cleaning"),
    ("Phenyl", "BOTTLE", "Cleaning"),
    ("Washing Soap Bar", "PIECE", "Cleaning"),
    ("Scrub Pad", "PACKET", "Cleaning"),
    ("Wiper", "PIECE", "Cleaning"),
    # Disposables (function/party ke liye)
    ("Paper Plates", "PACKET", "Disposables"),
    ("Paper Glasses", "PACKET", "Disposables"),
    ("Disposable Spoons", "PACKET", "Disposables"),
    ("Aluminium Foil", "PACKET", "Disposables"),
    ("Food Containers", "PACKET", "Disposables"),
    # Pickles & Sauces (achaar, sauce, chutney)
    ("Mango Pickle", "BOTTLE", "Pickles & Sauces"),
    ("Lemon Pickle", "BOTTLE", "Pickles & Sauces"),
    ("Chilli Pickle", "BOTTLE", "Pickles & Sauces"),
    ("Red Chilli Sauce", "BOTTLE", "Pickles & Sauces"),
    ("Green Chilli Sauce", "BOTTLE", "Pickles & Sauces"),
    # Other
    ("Papad", "PACKET", "Other"),
    ("Pickle", "BOTTLE", "Other"),
    ("Peanuts", "KG", "Other"),
    ("Cashew", "GRAM", "Other"),
    ("Raisins", "GRAM", "Other"),
    ("Almonds", "GRAM", "Other"),
    ("Makhana", "GRAM", "Other"),
    ("Walnuts", "GRAM", "Other"),
    ("Pistachios", "GRAM", "Other"),
    ("Chironji", "GRAM", "Other"),
    ("Dates", "KG", "Other"),
    ("Figs", "GRAM", "Other"),
    ("Jam", "BOTTLE", "Other"),
    ("Mayonnaise", "BOTTLE", "Other"),
    ("Peanut Butter", "BOTTLE", "Other"),
    ("Tamarind Chutney", "BOTTLE", "Other"),
    ("Roasted Chickpeas", "KG", "Other"),
    ("Soya Chunks", "KG", "Other"),
    ("Urad Badi", "PACKET", "Other"),
    ("Water Can", "PIECE", "Other"),
    ("Matchbox", "PACKET", "Other"),
    ("Other", "OTHER", "Other"),
]

# Hindi / Hinglish bol-chaal naam — purchase me "Aloo" likho to "Potato" milega.
# Key = English master name (exact), Value = alias list.
HINDI_ALIASES = {
    # Grains & Flour (Kirana)
    "Rice": ["Chawal", "Chaval"],
    "Wheat Flour": ["Aata", "Atta", "Gehu Aata"],
    "Maida": ["Maida"],
    "Suji": ["Suji", "Rava"],
    "Poha": ["Poha", "Chivda"],
    "Besan": ["Besan"],
    "Daliya": ["Daliya"],
    "Bajra Flour": ["Bajra Aata"],
    "Jowar Flour": ["Jowar Aata"],
    "Ragi Flour": ["Ragi Aata", "Nachni"],
    "Murmura": ["Murmura", "Kurmura"],
    "Sabudana": ["Sabudana"],
    "Macaroni": ["Macaroni"],
    "Pasta": ["Pasta"],
    "Vermicelli": ["Sevai", "Semai"],
    "Oats": ["Oats"],
    "Cornflour": ["Cornflour", "Corn Flour"],
    "Rice Flour": ["Chawal Aata"],
    # Dal & Pulses (Dal)
    "Toor Dal": ["Toor Dal", "Arhar Dal"],
    "Moong Dal": ["Moong Dal", "Dhuli Moong"],
    "Chana Dal": ["Chana Dal"],
    "Urad Dal": ["Urad Dal", "Dhuli Urad"],
    "Masoor Dal": ["Masoor Dal"],
    "Rajma": ["Rajma"],
    "Kabuli Chana": ["Kabuli Chana", "Chhole"],
    "Soyabean": ["Soyabean"],
    "Lobiya": ["Lobiya"],
    "White Peas": ["Safed Matar"],
    "Moong Sabut": ["Sabut Moong"],
    "Urad Sabut": ["Sabut Urad", "Kali Urad"],
    "Kala Chana": ["Kala Chana"],
    "Masoor Sabut": ["Sabut Masoor"],
    # Vegetables (Sabzi)
    "Potato": ["Aloo"],
    "Onion": ["Pyaz"],
    "Tomato": ["Tamatar"],
    "Mixed Vegetables": ["Mix Sabzi"],
    "Cauliflower": ["Phool Gobhi", "Gobhi"],
    "Cabbage": ["Patta Gobhi"],
    "Carrot": ["Gajar"],
    "Green Peas": ["Hari Matar", "Matar"],
    "Brinjal": ["Baingan"],
    "Ladyfinger": ["Bhindi"],
    "Pumpkin": ["Kaddu", "Sitaphal"],
    "Spinach": ["Palak"],
    "Green Chilli": ["Hari Mirch"],
    "Ginger": ["Adrak"],
    "Garlic": ["Lahsun"],
    "Coriander Leaves": ["Hara Dhaniya", "Dhaniya Patta"],
    "Mint Leaves": ["Pudina"],
    "Curry Leaves": ["Kadi Patta"],
    "Lemon": ["Nimbu"],
    "Cucumber": ["Kheera"],
    "Capsicum": ["Shimla Mirch"],
    "French Beans": ["Beans", "Phali"],
    "Bitter Gourd": ["Karela"],
    "Bottle Gourd": ["Lauki", "Ghiya"],
    "Ridge Gourd": ["Turai", "Tori"],
    "Drumstick": ["Sahjan", "Sahjan ki Phali"],
    "Raw Banana": ["Kachcha Kela"],
    "Sweet Potato": ["Shakarkand"],
    "Radish": ["Mooli"],
    "Beetroot": ["Chukandar"],
    "Mushroom": ["Mushroom"],
    "Coconut": ["Nariyal"],
    "Kathal": ["Kathal"],
    "Tinda": ["Tinda"],
    "Parwal": ["Parwal"],
    "Suran": ["Suran", "Jimikand"],
    "Kundru": ["Kundru"],
    "Sem Beans": ["Sem"],
    "Methi Saag": ["Methi"],
    "Bathua Saag": ["Bathua"],
    "Arbi": ["Arbi"],
    "Kairi": ["Kairi", "Kachcha Aam"],
    "Green Mango Powder": ["Amchur Powder"],
    "Turnip": ["Shalgam"],
    "Green Chickpeas": ["Hara Chana"],
    "Mustard Greens": ["Sarson Saag", "Sarson"],
    "Amaranth Greens": ["Chaulai"],
    "Arhar Pods": ["Arhar ki Phali"],
    "Cluster Beans": ["Gwar Phali"],
    "Raw Papaya": ["Kachcha Papita"],
    "Zucchini": ["Zucchini"],
    "Broccoli": ["Broccoli"],
    "Celery": ["Celery", "Ajmod"],
    "Lettuce": ["Lettuce", "Salad Patta"],
    "Spring Onion": ["Hara Pyaz", "Spring Onion"],
    "Leek": ["Leek"],
    "Turnip Greens": ["Shalgam ke Patte"],
    "Radish Greens": ["Mooli ke Patte"],
    "Basmati Rice": ["Basmati Chawal"],
    "Maize": ["Makka"],
    "Sattu": ["Sattu"],
    "Split Peas": ["Matar Dal"],
    "Mishri": ["Mishri"],
    "Chocolate Powder": ["Bournvita", "Chocolate Powder"],
    "Soybean Oil": ["Soyabean Tel"],
    "Refined Oil": ["Refined Tel"],
    "Sunflower Oil": ["Sunflower Oil", "Surajmukhi Tel"],
    "Groundnut Oil": ["Moongfali Tel"],
    "Sesame Oil": ["Til ka Tel"],
    "Coconut Oil": ["Nariyal Tel"],
    "Coriander Seeds": ["Sabut Dhaniya"],
    "White Pepper": ["Safed Mirch"],
    "Black Cardamom": ["Badi Elaichi"],
    "Nigella Seeds": ["Kalonji"],
    "Sabzi Masala": ["Sabzi Masala"],
    "Ginger Powder": ["Saunth", "Sonth"],
    "Onion Powder": ["Pyaaz Powder"],
    "Garlic Powder": ["Lahsun Powder"],
    "Sev": ["Sev", "Besan Sev"],
    "Bhujia": ["Bhujia"],
    "Chips": ["Chips"],
    "Walnuts": ["Akhrot"],
    "Pistachios": ["Pista"],
    "Chironji": ["Chironji"],
    "Dates": ["Khajoor"],
    "Figs": ["Anjeer"],
    "Jam": ["Jam"],
    "Mayonnaise": ["Mayonnaise"],
    "Peanut Butter": ["Peanut Butter"],
    "Tamarind Chutney": ["Imli ki Chutney"],
    "Roasted Chickpeas": ["Bhuna Chana", "Roasted Chana"],
    "Soya Chunks": ["Soya Chunks", "Soya Badi"],
    "Urad Badi": ["Badi", "Mangodi"],
    "Mango Pickle": ["Aam ka Achaar"],
    "Lemon Pickle": ["Nimbu ka Achaar"],
    "Chilli Pickle": ["Mirchi ka Achaar"],
    "Red Chilli Sauce": ["Red Chilli Sauce"],
    "Green Chilli Sauce": ["Green Chilli Sauce"],
    # Oil & Ghee (Tel)
    "Cooking Oil": ["Tel", "Khana Tel"],
    "Mustard Oil": ["Sarso Tel"],
    "Vanaspati": ["Vanaspati"],
    "Ghee": ["Ghee", "Desi Ghee"],
    # Spices & Masala (Masale, Namak)
    "Salt": ["Namak"],
    "Turmeric": ["Haldi"],
    "Red Chilli": ["Lal Mirch", "Sukhi Mirch"],
    "Coriander Powder": ["Sukha Dhaniya"],
    "Cumin": ["Jeera"],
    "Garam Masala": ["Garam Masala"],
    "Mixed Spices": ["Masale"],
    "Mustard Seeds": ["Rai", "Sarso Dana"],
    "Fenugreek Seeds": ["Methi Dana"],
    "Fennel Seeds": ["Saunf"],
    "Hing": ["Hing"],
    "Black Pepper": ["Kali Mirch"],
    "Amchur": ["Amchur"],
    "Black Salt": ["Kala Namak"],
    "Chaat Masala": ["Chaat Masala"],
    "Sambar Masala": ["Sambar Masala"],
    "Elaichi": ["Elaichi"],
    "Laung": ["Laung"],
    "Dalchini": ["Dalchini"],
    "Tej Patta": ["Tej Patta"],
    "Ajwain": ["Ajwain"],
    "Kasuri Methi": ["Kasuri Methi"],
    "Til": ["Til"],
    "Imli": ["Imli"],
    "Sendha Namak": ["Sendha Namak"],
    "Jeera Powder": ["Jeera Powder"],
    "Dhaniya Powder": ["Dhaniya Powder"],
    "Red Chilli Powder": ["Lal Mirch Powder"],
    "Chhole Masala": ["Chhole Masala"],
    "Kitchen King": ["Kitchen King"],
    "Biryani Masala": ["Biryani Masala"],
    "Ketchup": ["Ketchup", "Tomato Sauce", "Tomato Ketchup"],
    "Soy Sauce": ["Soya Sauce"],
    "Vinegar": ["Sirka"],
    "Coconut Powder": ["Nariyal Powder", "Nariyal Bura"],
    "Custard Powder": ["Custard"],
    # Dairy & Eggs
    "Milk": ["Doodh"],
    "Paneer": ["Paneer"],
    "Curd": ["Dahi"],
    "Butter": ["Makkhan"],
    "Milk Powder": ["Milk Powder"],
    "Egg": ["Anda"],
    "Khoya": ["Khoya", "Mawa"],
    "Chaas": ["Chaas", "Mattha"],
    # Bakery
    "Bread": ["Bread"],
    "Biscuits": ["Biscuit"],
    "Buns": ["Bun"],
    "Rusk": ["Rusk"],
    "Namkeen": ["Namkeen"],
    "Noodles": ["Noodles", "Atta Noodles"],
    "Cornflakes": ["Cornflakes"],
    "Baking Soda": ["Khane Wala Soda"],
    "Baking Powder": ["Baking Powder"],
    "Yeast": ["Yeast"],
    # Fuel
    "Gas Cylinder": ["Gas Cylinder", "Gas"],
    # Beverages (Cheeni, Chai)
    "Tea": ["Chai Patti", "Chai"],
    "Coffee": ["Coffee"],
    "Sugar": ["Cheeni", "Chini"],
    "Jaggery": ["Gud"],
    "Honey": ["Shahad"],
    "Sharbat": ["Sharbat"],
    # Fruits
    "Banana": ["Kela"],
    "Apple": ["Seb"],
    "Orange": ["Santra"],
    "Guava": ["Amrood"],
    "Papaya": ["Papita"],
    "Mango": ["Aam"],
    "Grapes": ["Angoor"],
    "Pomegranate": ["Anar"],
    "Watermelon": ["Tarbooj"],
    "Pineapple": ["Ananas"],
    # Cleaning
    "Detergent Powder": ["Surf", "Detergent"],
    "Dish Soap": ["Bartan Sabun"],
    "Floor Cleaner": ["Pochha Liquid"],
    "Garbage Bags": ["Kachra Bags"],
    "Broom": ["Jhadu"],
    "Mop": ["Pochha"],
    "Toilet Cleaner": ["Toilet Cleaner"],
    "Phenyl": ["Phenyl"],
    "Washing Soap Bar": ["Kapde Sabun"],
    "Scrub Pad": ["Scrub"],
    "Wiper": ["Wiper"],
    # Disposables
    "Paper Plates": ["Paper Plate"],
    "Paper Glasses": ["Paper Glass"],
    "Disposable Spoons": ["Disposable Chammach"],
    "Aluminium Foil": ["Foil"],
    "Food Containers": ["Dabba"],
    # Other
    "Papad": ["Papad"],
    "Pickle": ["Achar"],
    "Peanuts": ["Moongfali"],
    "Cashew": ["Kaju"],
    "Raisins": ["Kishmish"],
    "Almonds": ["Badam"],
    "Makhana": ["Makhana"],
    "Water Can": ["Pani Can"],
    "Matchbox": ["Machis"],
}
